apiVersion: batch/v1
kind: CronJob
metadata:
  name: podskiller
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      containers:
      - name: podskiller
        image: ditointernet/podskiller:0.1.0
        command: ["/podskiller", "-regex", "pod-name.+"]
      restartPolicy: OnFailure
