apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: podskiller
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: podskiller
          containers:
          - name: podskiller
            image: ditointernet/podskiller:0.1.0
            command: ["/podskiller", "-regex", "pod-name.+"]
          restartPolicy: OnFailure
