kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: podskiller
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podskiller
  namespace: default
subjects:
- kind: ServiceAccount
  name: podskiller
roleRef:
  kind: Role
  name: podskiller
  apiGroup: rbac.authorization.k8s.io
